name: Isaac Timothy Music
favicon: null
layout_spectrum: 0.98747
typography_spectrum: 0.35583
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090b24'
    - '#ffffff'
    - '#6674f2'
    - '#615837'
    - '#b3a570'
  brandStrength: 0.125
  lightness: 0.0625
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
